version: '3.1'

services:
  msrabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=uurdev
      - RABBITMQ_DEFAULT_PASS=uurdev@